name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - develop
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3

jobs:
    pre-commit:
        name: Lint with pre-commit
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                python-version: 3.11
            - uses: pre-commit/action@v3.0.0

    checks:
        name: Check Python ${{ matrix.python-version }} on ${{ matrix.runs-on }}
        if: github.event.pull_request.draft == false
        runs-on: ${{ matrix.runs-on }}
        needs: [pre-commit]
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.11", "3.12"]
                runs-on: [ubuntu-latest]

        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install package
              run: python -m pip install .[all]

            - name: Test package
              run: python -m pytest -ra --cov=prompto

            - name: Upload coverage report
              uses: codecov/codecov-action@v4.5.0

    docs:
        needs: [pre-commit, checks]
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3

          - uses: actions/setup-python@v4
            with:
              python-version: '3.11'

          - name: Apply mkdocs cache
            uses: actions/cache@v3
            with:
              key: mkdocs-material-${{ env.cache_id }}
              path: .cache
              restore-keys: |
                mkdocs-material-

          - name: Install doc dependencies via poetry
            run: |
              pip install poetry
              poetry install --extras dev

          - name: Build docs with gh-deploy --force
            run: |
              poetry run mkdocs gh-deploy --force
